[clog]

[sections]
"Bug Fixes" = ["fx", "fix"]
Builds = ["build"]
Documentation = ["docs"]
Features = ["ft", "feat", "feature"]
Refactorings = ["ref", "refactor"]
Reverts = ["rev", "revert"]
Styles = ["style"]
Tests = ["test"]
"Performance Improvements" = ["perf", "performance"]
