name: CI

on:
  pull_request: {}
  push:
    branches: [master]

jobs:
  build:
    name: Check, Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check
        run: cargo check --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --verbose
